CREATE DATABASE IF NOT EXISTS esp_toolbox
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'esp_user'@'%' IDENTIFIED BY 'esp_password';
GRANT ALL PRIVILEGES ON esp_toolbox.* TO 'esp_user'@'%';
FLUSH PRIVILEGES;

